### ISSUE TITLE
extreme high RAM usage + RuntimeError

### ISSUE THREAD

**Issue by Kkkassini** [exelents/try-gptj-generation#1]
Hello,

Tried to run it with stage 2/3 on a 128Go RAM machine,  always took 120Go+ RAM and then give the RuntimeError:

`
                              !! WARNING !!

  warnings.warn(WRONG_COMPILER_WARNING.format(
Detected CUDA files, patching ldflags
Emitting ninja build file /home/xingjian/.cache/torch_extensions/cpu_adam/build.ninja...
Building extension module cpu_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF cpu_adam.o.d -DTORCH_EXTENSION_NAME=cpu_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstd cpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/mbp/python38-virtualenv/lib64/python3.8/site-packages/deepspeed/ops/csrc/includes -I/usr/local/cuda/includ e -isystem /home/mbp/python38-virtualenv/lib64/python3.8/site-packages/torch/include -isystem /home/mbp/python38-virtualenv/lib64/python3.8/site-packages/tor ch/include/torch/csrc/api/include -isystem /home/mbp/python38-virtualenv/lib64/python3.8/site-packages/torch/include/TH -isystem /home/mbp/python38-virtualen v/lib64/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++1 4 -O3 -std=c++14 -L/usr/local/cuda/lib64 -lcudart -lcublas -g -Wno-reorder -march=native -fopenmp -D__AVX512__ -c /home/mbp/python38-virtualenv/lib64/python3 .8/site-packages/deepspeed/ops/csrc/adam/cpu_adam.cpp -o cpu_adam.o
[2/2] c++ cpu_adam.o custom_cuda_kernel.cuda.o -shared -L/home/mbp/python38-virtualenv/lib64/python3.8/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu - ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/usr/local/cuda/lib64 -lcudart -o cpu_adam.so
Loading extension module cpu_adam...
Time to load cpu_adam op: 33.33583927154541 seconds
Adam Optimizer #0 is created with AVX512 arithmetic capability.
Config: alpha=0.000010, betas=(0.800000, 0.999000), weight_decay=0.000000, adam_w=1
[2021-11-26 18:32:17,353] [INFO] [engine.py:1098:_configure_optimizer] Using DeepSpeed Optimizer param name adam as basic optimizer
[2021-11-26 18:32:17,381] [INFO] [engine.py:1106:_configure_optimizer] DeepSpeed Basic Optimizer = DeepSpeedCPUAdam
[2021-11-26 18:32:17,381] [INFO] [utils.py:43:is_zero_supported_optimizer] Checking ZeRO support for optimizer=DeepSpeedCPUAdam type=<class 'deepspeed.ops.ad am.cpu_adam.DeepSpeedCPUAdam'>
[2021-11-26 18:32:17,381] [INFO] [logging.py:69:log_dist] [Rank 0] Creating fp16 ZeRO stage 3 optimizer
Initializing ZeRO Stage 3
[2021-11-26 18:32:17,397] [INFO] [stage3.py:639:__init__] Reduce bucket size 3000000
[2021-11-26 18:32:17,397] [INFO] [stage3.py:640:__init__] Allgather bucket size 200000
Using /home/xingjian/.cache/torch_extensions as PyTorch extensions root...
/home/mbp/python38-virtualenv/lib64/python3.8/site-packages/torch/utils/cpp_extension.py:284: UserWarning:

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(WRONG_COMPILER_WARNING.format(
Emitting ninja build file /home/xingjian/.cache/torch_extensions/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF flatten_unflatten.o.d -DTORCH_EXTENSION_NAME=utils -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_ libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/mbp/python38-virtualenv/lib64/python3.8/site-packages/torch/include -isystem /home/mbp/python 38-virtualenv/lib64/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/mbp/python38-virtualenv/lib64/python3.8/site-packages/torch/i nclude/TH -isystem /home/mbp/python38-virtualenv/lib64/python3.8/site-packages/torch/include/THC -isystem /usr/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 - fPIC -std=c++14 -c /home/mbp/python38-virtualenv/lib64/python3.8/site-packages/deepspeed/ops/csrc/utils/flatten_unflatten.cpp -o flatten_unflatten.o
[2/2] c++ flatten_unflatten.o -shared -L/home/mbp/python38-virtualenv/lib64/python3.8/site-packages/torch/lib -lc10 -ltorch_cpu -ltorch -ltorch_python -o uti ls.so
Loading extension module utils...
Time to load utils op: 14.572093963623047 seconds
beginging get_train_batch_size = <function get_train_batch_size at 0x7f3f5042fe50>
train_batch = 16, micro_batch=None
[W ProcessGroupNCCL.cpp:1569] Rank 0 using best-guess GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially ca use a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[2021-11-26 18:38:24,067] [INFO] [logging.py:69:log_dist] [Rank 0] rank=0 time (ms) | init_optimizer_state: 336585.83
[2021-11-26 18:38:24,732] [INFO] [stage3.py:811:__init__] optimizer state initialized
[2021-11-26 18:38:27,218] [INFO] [logging.py:69:log_dist] [Rank 0] DeepSpeed Final Optimizer = adam
[2021-11-26 18:38:27,261] [INFO] [engine.py:788:_configure_lr_scheduler] DeepSpeed using configured LR scheduler = WarmupLR
[2021-11-26 18:38:27,262] [INFO] [logging.py:69:log_dist] [Rank 0] DeepSpeed LR Scheduler = <deepspeed.runtime.lr_schedules.WarmupLR object at 0x7f3f5fe70bb0 >
[2021-11-26 18:38:27,273] [INFO] [logging.py:69:log_dist] [Rank 0] step=0, skipped=0, lr=[1e-05], mom=[[0.8, 0.999]]
[2021-11-26 18:38:27,336] [INFO] [config.py:1044:print] DeepSpeedEngine configuration:
[2021-11-26 18:38:27,664] [INFO] [config.py:1048:print]   activation_checkpointing_config  {
    "partition_activations": false,
    "contiguous_memory_optimization": false,
    "cpu_checkpointing": false,
    "number_checkpoints": null,
    "synchronize_checkpoint_boundary": false,
    "profile": false
}
[2021-11-26 18:38:27,666] [INFO] [config.py:1048:print]   aio_config ................... {'block_size': 1048576, 'queue_depth': 8, 'thread_count': 1, 'single _submit': False, 'overlap_events': True}
[2021-11-26 18:38:27,667] [INFO] [config.py:1048:print]   allreduce_always_fp32 ........ False
[2021-11-26 18:38:27,667] [INFO] [config.py:1048:print]   amp_enabled .................. False
[2021-11-26 18:38:27,668] [INFO] [config.py:1048:print]   amp_params ................... False
[2021-11-26 18:38:27,685] [INFO] [config.py:1048:print]   autotuning_config ............ {
    "enabled": false,
    "start_step": null,
    "end_step": null,
    "metric_path": null,
    "arg_mappings": null,
    "metric": "throughput",
    "model_info": null,
    "results_dir": null,
    "exps_dir": null,
    "overwrite": true,
    "fast": true,
    "start_profile_step": 3,
    "end_profile_step": 5,
    "tuner_type": "gridsearch",
    "tuner_early_stopping": 5,
    "tuner_num_trials": 50,
    "model_info_path": null,
    "mp_size": 1,
    "max_train_batch_size": null,
    "min_train_batch_size": 1,
    "max_train_micro_batch_size_per_gpu": 1.024000e+03,
    "min_train_micro_batch_size_per_gpu": 1,
    "num_tuning_micro_batch_sizes": 3
}
[2021-11-26 18:38:27,689] [INFO] [config.py:1048:print]   bfloat16_enabled ............. False
[2021-11-26 18:38:27,689] [INFO] [config.py:1048:print]   checkpoint_tag_validation_enabled  True
[2021-11-26 18:38:27,689] [INFO] [config.py:1048:print]   checkpoint_tag_validation_fail  False
[2021-11-26 18:38:27,689] [INFO] [config.py:1048:print]   curriculum_enabled ........... False
[2021-11-26 18:38:27,689] [INFO] [config.py:1048:print]   curriculum_params ............ False
[2021-11-26 18:38:27,689] [INFO] [config.py:1048:print]   dataloader_drop_last ......... False
[2021-11-26 18:38:27,689] [INFO] [config.py:1048:print]   disable_allgather ............ False
[2021-11-26 18:38:27,689] [INFO] [config.py:1048:print]   dump_state ................... False
[2021-11-26 18:38:27,689] [INFO] [config.py:1048:print]   dynamic_loss_scale_args ...... {'init_scale': 4096, 'scale_window': 1000, 'delayed_shift': 2, 'min_ scale': 1}
[2021-11-26 18:38:27,689] [INFO] [config.py:1048:print]   eigenvalue_enabled ........... False
[2021-11-26 18:38:27,689] [INFO] [config.py:1048:print]   eigenvalue_gas_boundary_resolution  1
[2021-11-26 18:38:27,689] [INFO] [config.py:1048:print]   eigenvalue_layer_name ........ bert.encoder.layer
[2021-11-26 18:38:27,689] [INFO] [config.py:1048:print]   eigenvalue_layer_num ......... 0
[2021-11-26 18:38:27,689] [INFO] [config.py:1048:print]   eigenvalue_max_iter .......... 100
[2021-11-26 18:38:27,689] [INFO] [config.py:1048:print]   eigenvalue_stability ......... 1e-06
[2021-11-26 18:38:27,690] [INFO] [config.py:1048:print]   eigenvalue_tol ............... 0.01
[2021-11-26 18:38:27,690] [INFO] [config.py:1048:print]   eigenvalue_verbose ........... False
[2021-11-26 18:38:27,690] [INFO] [config.py:1048:print]   elasticity_enabled ........... False
[2021-11-26 18:38:27,692] [INFO] [config.py:1048:print]   flops_profiler_config ........ {
    "enabled": true,
    "profile_step": 1,
    "module_depth": -1,
    "top_modules": 1,
    "detailed": true,
    "output_file": null
}
[2021-11-26 18:38:27,693] [INFO] [config.py:1048:print]   fp16_enabled ................. True
[2021-11-26 18:38:27,693] [INFO] [config.py:1048:print]   fp16_master_weights_and_gradients  False
[2021-11-26 18:38:27,693] [INFO] [config.py:1048:print]   fp16_mixed_quantize .......... False
[2021-11-26 18:38:27,693] [INFO] [config.py:1048:print]   global_rank .................. 0
[2021-11-26 18:38:27,693] [INFO] [config.py:1048:print]   gradient_accumulation_steps .. 1
[2021-11-26 18:38:27,693] [INFO] [config.py:1048:print]   gradient_clipping ............ 0.0
[2021-11-26 18:38:27,693] [INFO] [config.py:1048:print]   gradient_predivide_factor .... 1.0
[2021-11-26 18:38:27,693] [INFO] [config.py:1048:print]   initial_dynamic_scale ........ 4096
[2021-11-26 18:38:27,693] [INFO] [config.py:1048:print]   loss_scale ................... 0
[2021-11-26 18:38:27,693] [INFO] [config.py:1048:print]   memory_breakdown ............. False
[2021-11-26 18:38:27,693] [INFO] [config.py:1048:print]   optimizer_legacy_fusion ...... False
[2021-11-26 18:38:27,693] [INFO] [config.py:1048:print]   optimizer_name ............... adam
[2021-11-26 18:38:27,694] [INFO] [config.py:1048:print]   optimizer_params ............. {'lr': 1e-05, 'betas': [0.8, 0.999], 'eps': 1e-08, 'weight_decay': 3 e-07}
[2021-11-26 18:38:27,699] [INFO] [config.py:1048:print]   pipeline ..................... {'stages': 'auto', 'partition': 'best', 'seed_layers': False, 'activ ation_checkpoint_interval': 0}
[2021-11-26 18:38:27,699] [INFO] [config.py:1048:print]   pld_enabled .................. False
[2021-11-26 18:38:27,699] [INFO] [config.py:1048:print]   pld_params ................... False
[2021-11-26 18:38:27,699] [INFO] [config.py:1048:print]   prescale_gradients ........... False
[2021-11-26 18:38:27,699] [INFO] [config.py:1048:print]   quantize_change_rate ......... 0.001
[2021-11-26 18:38:27,699] [INFO] [config.py:1048:print]   quantize_groups .............. 1
[2021-11-26 18:38:27,699] [INFO] [config.py:1048:print]   quantize_offset .............. 1000
[2021-11-26 18:38:27,699] [INFO] [config.py:1048:print]   quantize_period .............. 1000
[2021-11-26 18:38:27,700] [INFO] [config.py:1048:print]   quantize_rounding ............ 0
[2021-11-26 18:38:27,700] [INFO] [config.py:1048:print]   quantize_start_bits .......... 16
[2021-11-26 18:38:27,700] [INFO] [config.py:1048:print]   quantize_target_bits ......... 8
[2021-11-26 18:38:27,700] [INFO] [config.py:1048:print]   quantize_training_enabled .... False
[2021-11-26 18:38:27,700] [INFO] [config.py:1048:print]   quantize_type ................ 0
[2021-11-26 18:38:27,700] [INFO] [config.py:1048:print]   quantize_verbose ............. False
[2021-11-26 18:38:27,700] [INFO] [config.py:1048:print]   scheduler_name ............... WarmupLR
[2021-11-26 18:38:27,700] [INFO] [config.py:1048:print]   scheduler_params ............. {'warmup_min_lr': 0, 'warmup_max_lr': 3e-05, 'warmup_num_steps': 500 }
[2021-11-26 18:38:27,701] [INFO] [config.py:1048:print]   sparse_attention ............. None
[2021-11-26 18:38:27,701] [INFO] [config.py:1048:print]   sparse_gradients_enabled ..... False
[2021-11-26 18:38:27,701] [INFO] [config.py:1048:print]   steps_per_print .............. 2000
[2021-11-26 18:38:27,701] [INFO] [config.py:1048:print]   tensorboard_enabled .......... False
[2021-11-26 18:38:27,701] [INFO] [config.py:1048:print]   tensorboard_job_name ......... DeepSpeedJobName
[2021-11-26 18:38:27,701] [INFO] [config.py:1048:print]   tensorboard_output_path ......
[2021-11-26 18:38:27,701] [INFO] [config.py:1048:print]   train_batch_size ............. 16
[2021-11-26 18:38:27,701] [INFO] [config.py:1048:print]   train_micro_batch_size_per_gpu  16
[2021-11-26 18:38:27,701] [INFO] [config.py:1048:print]   use_quantizer_kernel ......... False
[2021-11-26 18:38:27,701] [INFO] [config.py:1048:print]   wall_clock_breakdown ......... True
[2021-11-26 18:38:27,701] [INFO] [config.py:1048:print]   world_size ................... 1
[2021-11-26 18:38:27,701] [INFO] [config.py:1048:print]   zero_allow_untested_optimizer  False
[2021-11-26 18:38:27,704] [INFO] [config.py:1048:print]   zero_config .................. {
    "stage": 3,
    "contiguous_gradients": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 3.000000e+06,
    "allgather_partitions": true,
    "allgather_bucket_size": 5.000000e+08,
    "overlap_comm": true,
    "load_from_fp32_weights": true,
    "elastic_checkpoint": true,
    "offload_param": {
        "device": null,
        "nvme_path": null,
        "buffer_count": 5,
        "buffer_size": 1.000000e+08,
        "max_in_cpu": 1.000000e+09,
        "pin_memory": false
    },
    "offload_optimizer": {
        "device": null,
        "nvme_path": null,
        "buffer_count": 4,
        "pin_memory": false,
        "pipeline_read": false,
        "pipeline_write": false,
        "fast_init": false
    },
    "sub_group_size": 1.000000e+06,
    "prefetch_bucket_size": 2.000000e+05,
    "param_persistence_threshold": 1.000000e+05,
    "max_live_parameters": 6.000000e+06,
    "max_reuse_distance": 1.000000e+08,
    "gather_fp16_weights_on_model_save": true,
    "ignore_unused_parameters": true,
    "round_robin_gradients": false,
    "legacy_stage1": false
}
[2021-11-26 18:38:27,704] [INFO] [config.py:1048:print]   zero_enabled ................. True
[2021-11-26 18:38:27,704] [INFO] [config.py:1048:print]   zero_optimization_stage ...... 3
[2021-11-26 18:38:27,709] [INFO] [config.py:1050:print]   json = {
    "train_batch_size": 16,
    "steps_per_print": 2.000000e+03,
    "fp16": {
        "enabled": true,
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 12,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "flops_profiler": {
        "enabled": true,
        "profile_step": 1,
        "module_depth": -1,
        "top_modules": 1,
        "detailed": true,
        "output_file": null
    },
    "zero_optimization": {
        "stage": 3,
        "cpu_offload": true,
        "cpu_offload_params": true,
        "overlap_comm": true,
        "contiguous_gradients": true,
        "stage3_max_live_parameters": 6.000000e+06,
        "stage3_max_reuse_distance": 1.000000e+08,
        "stage3_prefetch_bucket_size": 2.000000e+05,
        "stage3_param_persitance_threshold": 1.000000e+05,
        "reduce_bucket_size": 3.000000e+06,
        "sub_group_size": 1.000000e+06,
        "stage3_gather_fp16_weights_on_model_save": true
    },
    "optimizer": {
        "type": "Adam",
        "params": {
            "lr": 1e-05,
            "betas": [0.8, 0.999],
            "eps": 1e-08,
            "weight_decay": 3e-07
        }
    },
    "scheduler": {
        "type": "WarmupLR",
        "params": {
            "warmup_min_lr": 0,
            "warmup_max_lr": 3e-05,
            "warmup_num_steps": 500
        }
    },
    "wall_clock_breakdown": false
}
Using /home/xingjian/.cache/torch_extensions as PyTorch extensions root...
No modifications detected for re-loaded extension module utils, skipping build step...
Loading extension module utils...
Time to load utils op: 0.19681477546691895 seconds
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Traceback (most recent call last):
  File "gptj_run.py", line 11, in <module>
    out = model.generate(
  File "/userfs/gptjh/gptj_deepspeed/gptj_wrapper.py", line 198, in generate
    res = super().generate(
  File "/home/mbp/python38-virtualenv/lib64/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/mbp/python38-virtualenv/lib64/python3.8/site-packages/transformers/generation_utils.py", line 1017, in generate
    return self.sample(
  File "/home/mbp/python38-virtualenv/lib64/python3.8/site-packages/transformers/generation_utils.py", line 1531, in sample
    outputs = self(
  File "/userfs/gptjh/gptj_deepspeed/gptj_wrapper.py", line 214, in __call__
    return self.model(**kwargs)
  File "/home/mbp/python38-virtualenv/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mbp/python38-virtualenv/lib64/python3.8/site-packages/deepspeed/runtime/engine.py", line 1597, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/mbp/python38-virtualenv/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1057, in _call_impl
    for hook in itertools.chain(
RuntimeError: OrderedDict mutated during iteration
`

**Comment by exelents** [comment]
Hi.
Did you wrote your own generation code in file gptj_run.py ? What is in this file? Can you try inwoke model.generate() method under no_grad() statement? Like this:
```

with torch.no_grad():
    <your generation code here>
```

**Comment by Kkkassini** [comment]
> Hi. Did you wrote your own generation code in file gptj_run.py ? What is in this file? Can you try inwoke model.generate() method under no_grad() statement? Like this:
> 
> ```
> 
> with torch.no_grad():
>     <your generation code here>
> ```

Hello, thanks for the response. Here's the code in gptj_run.py :
````
import torch
import gptj_wrapper as gptj
import datetime

model = gptj.GPTJ(stage=3)
eos_newline = model.tokenizer("<|endoftext|>")['input_ids'][0]

with torch.no_grad():
    text = "Today is a sunny day"
    start = datetime.datetime.now()
    out = model.generate(
        text=text,
        max_length=150,
        #         num_beams=5,
        do_sample=True,
        temperature=0.8,
        top_k=5,
        top_p=0.9,
        no_repeat_ngram_size=2,
        early_stopping=True,
        #         num_return_sequences=1,
        use_cache=False,
        eos_token_id=eos_newline
    )
    duration = datetime.datetime.now() - start
    for o in out:
        print("\n\n\n")
        print(o[len(text):])
    print(f"\n\nDuration = {duration.total_seconds()}")

**Comment by Kkkassini** [comment]
if i use stage 2 config:
```
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module cpu_adam...
Time to load cpu_adam op: 1.5404539108276367 seconds
Adam Optimizer #0 is created with AVX512 arithmetic capability.
Config: alpha=0.000010, betas=(0.800000, 0.999000), weight_decay=0.000000, adam_w=1
[2021-11-29 14:28:22,459] [INFO] [engine.py:1098:_configure_optimizer] Using DeepSpeed Optimizer param name adam as basic optimizer
[2021-11-29 14:28:22,476] [INFO] [engine.py:1106:_configure_optimizer] DeepSpeed Basic Optimizer = DeepSpeedCPUAdam
[2021-11-29 14:28:22,476] [INFO] [utils.py:43:is_zero_supported_optimizer] Checking ZeRO support for optimizer=DeepSpeedCPUAdam type=<class 'deepspeed.ops.adam.cpu_adam.DeepSpeedCPUAdam'>
[2021-11-29 14:28:22,476] [INFO] [logging.py:69:log_dist] [Rank 0] Creating fp16 ZeRO stage 2 optimizer
[2021-11-29 14:28:22,476] [INFO] [stage2.py:113:__init__] Reduce bucket size 200000000
[2021-11-29 14:28:22,476] [INFO] [stage2.py:114:__init__] Allgather bucket size 200000000
[2021-11-29 14:28:22,476] [INFO] [stage2.py:115:__init__] CPU Offload: True
[2021-11-29 14:28:22,476] [INFO] [stage2.py:116:__init__] Round robin gradient partitioning: False
Using /home/xingjian/.cache/torch_extensions as PyTorch extensions root...
Emitting ninja build file /home/xingjian/.cache/torch_extensions/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.6622180938720703 seconds
Rank: 0 partition count [1] and sizes[(6050882784, False)]
[W ProcessGroupNCCL.cpp:1569] Rank 0 using best-guess GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[2021-11-29 14:29:09,582] [INFO] [utils.py:822:see_memory_usage] Before initializing optimizer states
[2021-11-29 14:29:09,583] [INFO] [utils.py:823:see_memory_usage] MA 11.77 GB         Max_MA 11.77 GB         CA 11.78 GB         Max_CA 12 GB
[2021-11-29 14:29:09,583] [INFO] [utils.py:831:see_memory_usage] CPU Virtual Memory:  used = 70.57 GB, percent = 56.2%
Killed
```

**Comment by exelents** [comment]
Which GPU do you use? I'm not sure, but maybe 12 Gb of GPU memory isn't enough for this model... I use RTX 3090, it has 24 Gb of memory, that's why I don't have OOM error. You can ask this information on this discord server:
https://discord.gg/2AmPVxnz

12 Gb - it is only size of model's weights, but you also need memory for batch tensors...

**Comment by exelents** [comment]
Also try stage=0, maybe you could run model on CPU.
